Final changes
Usagib/EmbeddingImagesAndVideo pull request #2
Opened 2019-08-15 21:42 UTC by Usagib

final changes for project, updated readme file and added css styling

2019-08-16 18:47 UTC, samgaco requested changes
### Hi @Usagib and @sebastianlujan :vulcan_salute: 

### The project is looking brilliant so far :ok_hand: , some things to address:

* There should be at least three embedded images in the rightmost part of the navbar. In the original page you can find some inspiration:
![ok](https://user-images.githubusercontent.com/34820784/63189760-033bee80-c065-11e9-90d9-4590f86ea0c3.png)
* **[OPTIONAL]** Good work on the readme file, try to go through a markdown [cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to see how to make it look even better.
* Read on semantic HTML elements, you should try to implement it. For example, you could use `<main>` for the dominant content of the body.

### Please, work on these changes and submit back for another code review when you are done. Remember to commit and request a new code review on this branch, no need to open a new one. Regards! :muscle:

2019-08-16 18:47 UTC, samgaco commented on CSS/style.css
>    color: red;
It's better to delete commented code

2019-08-20 16:33 UTC, Usagib commented
Hello Team!, we have made the modifications required! 
please review our code ;)

2019-08-20 21:53 UTC, Oghenebrume50 approved these changes
Hi team, good job, it's is a wrap :smiley:  please go ahead and merge to master. Then submit a project completion form for this project, good luck for the next project. :+1:

2019-08-21 15:30 UTC, merged